service: datahog

frameworkVersion: '2'

provider:
  name: aws
  stage: dev
  runtime: nodejs14.x
  region: eu-west-1
  lambdaHashingVersion: 20201221
  environment:
    NODE_OPTIONS: '--enable-source-maps=true'
  
plugins:
  - serverless-plugin-typescript

functions:
  publisher:
    handler: functions/publisher/handler.handle
    role: publisherRole
    memorySize: 128
    events:
      - http:
          path: /collect
          method: post

  subscriber:
    handler: functions/subscriber/handler.handle
    role: subscriberRole
    memorySize: 128
    events:
      - sqs: 
          arn: arn:aws:sqs:eu-west-1:404356446913:collections
          batchSize: 1

resources: ${file(config/resources.yml)}
