service: datahog

frameworkVersion: '2'

provider:
  name: aws
  stage: dev
  runtime: nodejs14.x
  region: eu-west-1
  lambdaHashingVersion: 20201221
  environment:
    NODE_OPTIONS: '--enable-source-maps=true'
    BACKOFF_MULTIPLIER: 90
    PROVIDER_API_BASE_URL: 'https://datahog.lemonjs.uk'
    COLLECTIONS_QUEUE_NAME: https://sqs.eu-west-1.amazonaws.com/404356446913/collections
  
plugins:
  - serverless-plugin-typescript
  - serverless-domain-manager

custom:
  customDomain:
    domainName: datahog.lemonjs.uk
    apiType: rest

functions:
  providers:
    handler: functions/providers/handler.handle
    memorySize: 128
    events:
      - http:
          path: /providers/{id}
          method: get

  publisher:
    handler: functions/publisher/handler.handle
    role: publisherRole
    memorySize: 128
    events:
      - http:
          path: /collect
          method: post
          request:
            schemas:
              application/json: ${file(functions/publisher/schema.json)}

  subscriber:
    handler: functions/subscriber/handler.handle
    role: subscriberRole
    memorySize: 128
    events:
      - sqs: 
          arn: arn:aws:sqs:eu-west-1:404356446913:collections
          batchSize: 1

resources: ${file(config/resources.yml)}
