service: datahog

frameworkVersion: '2'
variablesResolutionMode: 20210326

provider:
  name: aws
  stage: dev
  runtime: nodejs14.x
  region: eu-west-1
  lambdaHashingVersion: 20201221
  environment:
    NODE_OPTIONS: '--enable-source-maps=true'
    BACKOFF_MULTIPLIER: 90
    REGION: ${self:custom.region}
    PROVIDER_API_BASE_URL: https://datahog.lemonjs.uk
    COLLECTIONS_QUEUE_NAME: https://sqs.${self:custom.region}.amazonaws.com/${self:custom.accountId}/collections
  
plugins:
  - serverless-plugin-typescript
  - serverless-domain-manager

custom:
  accountId: ${file(deploy/account.js):getAccountId}
  region: eu-west-1
  customDomain:
    domainName: datahog.lemonjs.uk
    apiType: rest

functions:
  providers:
    handler: functions/providers/handler.handle
    memorySize: 128
    events:
      - http:
          path: /providers/{id}
          method: get
          request:
            parameters:
              paths:
                id: true

  publisher:
    handler: functions/publisher/handler.handle
    role: publisherRole
    memorySize: 128
    events:
      - http:
          path: /collect
          method: post
          request:
            schemas:
              application/json: ${file(functions/publisher/schema.json)}

  subscriber:
    handler: functions/subscriber/handler.handle
    role: subscriberRole
    memorySize: 128
    events:
      - sqs: 
          arn: arn:aws:sqs:${self:custom.region}:${self:custom.accountId}:collections
          batchSize: 1

resources: ${file(config/resources.yml)}
