Type: AWS::IAM::Role
Properties:
  Path: /
  RoleName: publisher-${self:custom.region}-lambda-role
  AssumeRolePolicyDocument: ${file(config/permissions/assume-role.yml)}
  Policies:
    - PolicyName: publisher-${self:custom.region}-policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - ${file(config/permissions/logging.yml)}
          - ${file(config/permissions/sqs.yml)}
