Type: AWS::IAM::Role
Properties:
  Path: /
  RoleName: publisher-eu-west-1-lambda-role
  AssumeRolePolicyDocument: ${file(config/permissions/assume-role.yml)}
  Policies:
    - PolicyName: publisher-eu-west-1-policy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - ${file(config/permissions/logging.yml)}
          - ${file(config/permissions/sqs.yml)}
